### ISSUE TITLE
Upload to Jupyter Dashboard Server should include associated resources

### ISSUE THREAD

**Issue by nitind** [jupyter-incubator/dashboards_bundlers#14]
*Deploy as Dashboard on Jupyter Dashboard Server* currently sends just the notebook to the Jupyter Dashboards Server. Once jupyter-incubator/dashboards_nodejs_app#79 is resolved, change from uploading just the notebook file to uploading a zip containing the notebook and its associated resources.

**Comment by parente** [comment]
@dalogsdon @jhpedemonte Nitin is going to start looking at how to package up additional assets (e.g., declarative widget imports, associated HTML/CSS files for custom polymer widgets) and upload them in a zip bundle also containing the ipynb notebook. This is the sister issue to jupyter-incubator/dashboards_nodejs_app#79 which will have to handle unpacking the zip and making the static assets in it web addressable.

We'll keep the change in a PR here until both sides are ready to switch. We'll have a chat next week to make sure we've got the design right and don't run into the bundling / path hell we had with Polymer when we did this the first time round with the PHP app (e.g., the bundle has to include all the polymer widgets and polymer itself because polymer / declarative widgets is picky about where it looks for its components: they all have to be under the same path).

**Comment by nitind** [comment]
Created https://github.com/jupyter-incubator/dashboards_bundlers/pull/19 . Since it reuses the bundle_web_static function, which always adds gridstack et al, it will always be a zip rather than a plain notebook being sent to the dashboards server.
